# Generated by Django 4.1.7 on 2023-03-15 10:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, upload_to='')),
                ('name', models.CharField(default='None', max_length=30)),
                ('c1', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('c2', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('c3', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('c4', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('c5', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('c6', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('c7', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('c8', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('c9', models.CharField(choices=[('1', 'Choose...'), ('2', 'name'), ('3', 'job'), ('4', 'company'), ('5', 'date'), ('6', 'phone'), ('7', 'address'), ('8', 'city'), ('9', 'country'), ('10', 'email')], default='Choose...', max_length=30)),
                ('n1', models.CharField(blank=True, default='None', max_length=30)),
                ('n2', models.CharField(blank=True, default='None', max_length=30)),
                ('n3', models.CharField(blank=True, default='None', max_length=30)),
                ('n4', models.CharField(blank=True, default='None', max_length=30)),
                ('n5', models.CharField(blank=True, default='None', max_length=30)),
                ('n6', models.CharField(blank=True, default='None', max_length=30)),
                ('n7', models.CharField(blank=True, default='None', max_length=30)),
                ('n8', models.CharField(blank=True, default='None', max_length=30)),
                ('n9', models.CharField(blank=True, default='None', max_length=30)),
                ('o1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('o2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('o3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('o4', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('o5', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('o6', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('o7', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('o8', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('o9', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('rows', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
